### ISSUE TITLE
O tempo de jogo deveria parar?

### ISSUE THREAD

**Issue by luizf-s** [PedroHumberto/memoryGameJS#1]
Após finalizar uma rodada o cronômetro continuou contando.

Testado em Google Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by PedroHumberto** [comment]
Problema resolvido, armazenei o tempo na variável 'interval' e ao final do jogo ao alcançar 8 pontos é executado o metodo clearInterval(interval)
